language: java
sudo: false
script:
  - ./mvnw clean
  - ./mvnw install -DskipTests
  - ./mvnw test -Dcucumber.options="--tags '@AcctTest'"
  - ./mvnw test -Dcucumber.options="--tags '@LoginTest'"
  - ./mvnw test -Dcucumber.options="--tags '@MobileTest'"
